shared void run() {
  throw Exception("the_error");
}